"use client";
import {Blocks,Box,Camera,CheckCircle2,Copy,Download,FileJson,FolderOpen,Focus,Layers3,Plus,RotateCcw,Trash2,TriangleAlert,Upload} from "lucide-react";
import {useMemo,useRef,useState} from "react";
import {AssemblyViewer} from "../packages/renderer/src/assembly-viewer";
import {billOfMaterials,CATALOGUE,COLOURS,createPart,defaultAssembly,exportLDraw,parseAssembly,serializeAssembly,snapPosition,validateAssembly,type AssemblyDocument,type PartInstance} from "../packages/renderer/src/assembly";
import {resolveLDraw,sourceMap,type LDrawSourceMap} from "../packages/renderer/src/ldraw-resolver";

const download=(name:string,text:string,type:string)=>{const url=URL.createObjectURL(new Blob([text],{type})),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)};

export default function Home(){
 const folderInput=useRef<HTMLInputElement>(null),importInput=useRef<HTMLInputElement>(null);
 const [library,setLibrary]=useState<LDrawSourceMap|null>(null),[indexedCount,setIndexedCount]=useState(0),[loading,setLoading]=useState(false),[message,setMessage]=useState("Load the official LDraw folder to render real parts");
 const [document,setDocument]=useState<AssemblyDocument>(()=>defaultAssembly()),[selectedId,setSelectedId]=useState("brick-1"),[cataloguePart,setCataloguePart]=useState("3001");
 const [ortho,setOrtho]=useState(false),[wire,setWire]=useState(false),[resetKey,setResetKey]=useState(0);
 const models=useMemo(()=>{const cache=new Map();if(library)for(const part of CATALOGUE)if(library.has(part.file))cache.set(part.partNumber,resolveLDraw(library,part.file));return cache},[library]);
 const issues=validateAssembly(document.parts),invalidIds=new Set(issues.flatMap(issue=>issue.partIds)),bom=billOfMaterials(document.parts);
 const selected=document.parts.find(part=>part.id===selectedId),available=CATALOGUE.filter(part=>models.has(part.partNumber));
 async function openLibrary(list:FileList|null){
  if(!list?.length)return;setLoading(true);setMessage("Indexing LDraw files…");
  try{const entries=await Promise.all(Array.from(list).filter(file=>file.name.toLowerCase().endsWith(".dat")).map(async file=>[file.webkitRelativePath||file.name,await file.text()] as [string,string]));const map=sourceMap(entries);const count=[...map.keys()].filter(key=>/^parts\/[^/]+\.dat$/.test(key)).length;setLibrary(map);setIndexedCount(count);const found=CATALOGUE.filter(part=>map.has(part.file)).length;setMessage(`${found}/${CATALOGUE.length} controlled parts ready`)}catch(error){setMessage(error instanceof Error?error.message:"Could not read that library")}finally{setLoading(false)}
 }
 function updateSelected(change:(part:PartInstance)=>PartInstance){if(!selectedId)return;setDocument(value=>({...value,parts:value.parts.map(part=>part.id===selectedId?change(part):part)}))}
 function move(dx:number,dy:number,dz:number){updateSelected(part=>({...part,position:snapPosition([part.position[0]+dx,Math.max(0,part.position[1]+dy),part.position[2]+dz])}))}
 function addPart(){setDocument(value=>{const next=createPart(value.parts,cataloguePart,selected?[selected.position[0]+20,selected.position[1],selected.position[2]]:[0,0,0],selected?.colour??4);setSelectedId(next.id);return{...value,parts:[...value.parts,next]}})}
 function duplicate(){if(!selected)return;setDocument(value=>{const next={...selected,id:createPart(value.parts,selected.partNumber).id,position:snapPosition([selected.position[0]+20,selected.position[1],selected.position[2]])};setSelectedId(next.id);return{...value,parts:[...value.parts,next]}})}
 function remove(){if(!selected)return;setDocument(value=>{const parts=value.parts.filter(part=>part.id!==selected.id);setSelectedId(parts[0]?.id??"");return{...value,parts}})}
 async function importDocument(file?:File){if(!file)return;try{const next=parseAssembly(await file.text());setDocument(next);setSelectedId(next.parts[0]?.id??"");setMessage(`Imported ${next.parts.length} part instances`)}catch(error){setMessage(error instanceof Error?error.message:"Could not import assembly")}}
 return <main className="app-shell assembly-shell">
  <header className="topbar"><div className="brand-mark"><Blocks size={21}/></div><div><strong>BRICKFORGE</strong><span>AI</span></div><div className="milestone">ASSEMBLY WORKSPACE · M2.3</div><div className="health"><i className={issues.length?"warn":""}/>{loading?"Reading library…":library?`${indexedCount} parts indexed · ${message}`:message}</div></header>
  <aside className="sidebar assembly-sidebar"><nav><p>BUILD</p><a className="active"><Box size={17}/>Assembly editor</a><a><CheckCircle2 size={17}/>Validation <em>{issues.length}</em></a><a><FileJson size={17}/>Bill of materials <em>{document.parts.length}</em></a></nav><div className="source-card"><span>GEOMETRY SOURCE</span><b>{library?"Official LDraw library":"No library loaded"}</b><small>{library?`${available.length}/${CATALOGUE.length} controlled parts resolved`:"Local files stay in your browser"}</small><p>Each part geometry is resolved once, cached by part number, and reused by every instance.</p></div></aside>
  <section className="assembly-workspace">
   <div className="assembly-heading"><div><p>REAL MULTI-PART BUILD</p><h1>{document.name}</h1><span>{document.parts.length} placed parts · {bom.reduce((sum,row)=>sum+row.quantity,0)} total in BOM</span></div><button className="secondary-upload" onClick={()=>importInput.current?.click()}><Upload size={16}/>Import JSON</button><button className="upload" onClick={()=>folderInput.current?.click()}><FolderOpen size={17}/>{loading?"Loading…":"Load LDraw library"}</button><input ref={folderInput} hidden type="file" multiple {...({webkitdirectory:"",directory:""} as React.InputHTMLAttributes<HTMLInputElement>)} onChange={event=>openLibrary(event.target.files)}/><input ref={importInput} hidden type="file" accept=".json,application/json" onChange={event=>importDocument(event.target.files?.[0])}/></div>
   <div className="assembly-grid">
    <section className="build-panel">
     <div className="add-bar"><select value={cataloguePart} onChange={event=>setCataloguePart(event.target.value)}>{CATALOGUE.map(part=><option key={part.partNumber} value={part.partNumber} disabled={!!library&&!models.has(part.partNumber)}>{part.partNumber} · {part.name}{library&&!models.has(part.partNumber)?" (missing)":""}</option>)}</select><button onClick={addPart}><Plus size={16}/>Add part</button><span>20 LDU stud grid · 8 LDU plate grid</span></div>
     <div className="view-toolbar"><button className={!ortho?"selected":""} onClick={()=>setOrtho(false)}><Camera size={15}/>Perspective</button><button className={ortho?"selected":""} onClick={()=>setOrtho(true)}><Focus size={15}/>Orthographic</button><button className={wire?"selected":""} onClick={()=>setWire(value=>!value)}><Layers3 size={15}/>Wireframe</button><button onClick={()=>setResetKey(value=>value+1)}><RotateCcw size={15}/>Reset view</button></div>
     <AssemblyViewer parts={document.parts} models={models} selectedId={selectedId} invalidIds={invalidIds} orthographic={ortho} wireframe={wire} resetKey={resetKey} onSelect={setSelectedId}/>
     {!library&&<div className="library-empty"><FolderOpen size={28}/><b>Load the official LDraw folder</b><span>The interlocking test assembly is ready; real 3001 geometry appears once the local library is selected.</span><button onClick={()=>folderInput.current?.click()}>Choose folder</button></div>}
    </section>
    <aside className="assembly-inspector">
     <div className="inspector-head"><span>SELECTED INSTANCE</span><span className={`status ${issues.length?"warning":""}`}>{issues.length?`${issues.length} ISSUE${issues.length===1?"":"S"}`:"BUILD VALID"}</span></div>
     {selected?<><h2>{selected.id}</h2><p>{CATALOGUE.find(part=>part.partNumber===selected.partNumber)?.name} · {selected.partNumber}.dat</p><div className="move-pad"><button onClick={()=>move(0,0,-20)}>Z−</button><button onClick={()=>move(0,8,0)}>Y+</button><button onClick={()=>move(-20,0,0)}>X−</button><button className="rotate" onClick={()=>updateSelected(part=>({...part,rotation:((part.rotation+90)%360) as PartInstance["rotation"]}))}>↻ 90°</button><button onClick={()=>move(20,0,0)}>X+</button><button onClick={()=>move(0,-8,0)}>Y−</button><button onClick={()=>move(0,0,20)}>Z+</button></div><dl className="position-readout"><div><dt>X</dt><dd>{selected.position[0]}</dd></div><div><dt>Y</dt><dd>{selected.position[1]}</dd></div><div><dt>Z</dt><dd>{selected.position[2]}</dd></div><div><dt>Rotation</dt><dd>{selected.rotation}°</dd></div></dl><label className="colour-label">COLOUR<select value={selected.colour} onChange={event=>updateSelected(part=>({...part,colour:Number(event.target.value)}))}>{COLOURS.map(colour=><option key={colour.code} value={colour.code}>{colour.name}</option>)}</select></label><div className="instance-actions"><button onClick={duplicate}><Copy size={15}/>Duplicate</button><button className="danger" onClick={remove}><Trash2 size={15}/>Delete</button></div></>:<div className="nothing-selected">Select a brick in the scene.</div>}
     <button className="reset-assembly" onClick={()=>{const next=defaultAssembly();setDocument(next);setSelectedId(next.parts[0].id)}}><RotateCcw size={15}/>Reset interlocking assembly</button>
    </aside>
    <aside className="validation-panel"><div className="panel-title"><span>VALIDATION</span>{issues.length?<TriangleAlert size={17}/>:<CheckCircle2 size={17}/>}</div>{issues.length?<ul>{issues.map((issue,index)=><li key={`${issue.kind}-${index}`}><b>{issue.kind.replace("-"," ")}</b><span>{issue.message}</span></li>)}</ul>:<div className="all-valid"><CheckCircle2 size={22}/><div><b>Assembly is buildable</b><span>No collisions, off-grid parts, or floating components.</span></div></div>}<div className="panel-title bom-title"><span>BILL OF MATERIALS</span><b>{document.parts.length}</b></div><div className="bom-list">{bom.map(row=><div key={`${row.partNumber}-${row.colour}`}><i style={{background:COLOURS.find(colour=>colour.code===row.colour)?.hex}}/><span><b>{row.partNumber} · {row.name}</b><small>{row.colourName}</small></span><strong>×{row.quantity}</strong></div>)}</div><div className="export-actions"><button onClick={()=>download("brickforge-assembly.json",serializeAssembly(document),"application/json")}><Download size={15}/>JSON</button><button onClick={()=>download("brickforge-assembly.ldr",exportLDraw(document),"text/plain")}><Download size={15}/>LDraw</button></div></aside>
   </div>
  </section>
 </main>;
}
