"use client";
import { ArrowRight,Blocks,Box,Check,ChevronRight,Download,Eye,ImagePlus,Layers3,LoaderCircle,ShieldCheck,Sparkles,Trash2 } from "lucide-react";
import { useMemo,useRef,useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { analyseImage,mergeProfiles,type AnalysedImage } from "../packages/reconstruction/src/image-analysis";
import { reconstructFromProfiles,type ReconstructionResult } from "../packages/reconstruction/src/reconstruct";
import { billOfMaterials,CATALOGUE,COLOURS,exportLDraw,serializeAssembly,type PartInstance } from "../packages/renderer/src/assembly";

type Angle="Front"|"Right"|"Back"|"Left"|"Detail";
type Photo={ id: string; name: string; angle: Angle; analysis: AnalysedImage ;};
const ANGLES: Angle[]=["Front","Right","Back","Left","Detail"];
const SIZES={ Study: { layers: 10,width: 10,depth: 8 },Balanced: { layers: 16,width: 16,depth: 12 },Display: { layers: 24,width: 24,depth: 18 } } as const;
const download=(name: string,text: string,type: string) => { const url=URL.createObjectURL(new Blob([text],{ type })),link=document.createElement("a"); link.href=url; link.download=name; link.click(); URL.revokeObjectURL(url) ;};

function LayerDiagram({ parts }: { parts: PartInstance[] ;}) {
  const boxes=parts.map(part => { const definition=CATALOGUE.find(item => item.partNumber===part.partNumber)!; const rotated=part.rotation===90||part.rotation===270,x=(rotated? definition.widthStuds:definition.lengthStuds)*20,z=(rotated? definition.lengthStuds:definition.widthStuds)*20; return { part,x,z,minX: part.position[0]-x/2,maxX: part.position[0]+x/2,minZ: part.position[2]-z/2,maxZ: part.position[2]+z/2 } ;}),minX=Math.min(...boxes.map(box => box.minX)),maxX=Math.max(...boxes.map(box => box.maxX)),minZ=Math.min(...boxes.map(box => box.minZ)),maxZ=Math.max(...boxes.map(box => box.maxZ)),width=Math.max(20,maxX-minX),depth=Math.max(20,maxZ-minZ);
  return <div className="layer-map" aria-label="Top view of this instruction layer">{boxes.map(box => <i key={box.part.id} title={`${box.part.partNumber} at X ${box.part.position[0]}, Z ${box.part.position[2]}`} style={{ left: `${(box.minX-minX)/width*86+7}%`,top: `${(box.minZ-minZ)/depth*78+11}%`,width: `${box.x/width*86}%`,height: `${box.z/depth*78}%`,background: COLOURS.find(value => value.code===box.part.colour)?.hex }}><span>{box.part.partNumber}</span></i>)}</div>;
}

export default function Reconstruction() {
  const input=useRef<HTMLInputElement>(null),[photos,setPhotos]=useState<Photo[]>([]),[analysing,setAnalysing]=useState(false),[error,setError]=useState(""),[size,setSize]=useState<keyof typeof SIZES>("Balanced"),[hollow,setHollow]=useState(true),[colour,setColour]=useState(71),[result,setResult]=useState<ReconstructionResult|null>(null),[step,setStep]=useState(0);
  const bom=useMemo(() => result? billOfMaterials(result.document.parts):[],[result]);
  async function addPhotos(files: FileList|null) { if(!files?.length) return; setAnalysing(true); setError(""); setResult(null); try { const analysed=await Promise.all(Array.from(files).slice(0,8).map(file => analyseImage(file))); setPhotos(current => [...current,...analysed.map((analysis,index) => ({ id: `${Date.now()}-${index}`,name: files[index].name,angle: ANGLES[(current.length+index)%ANGLES.length],analysis }))].slice(0,8)) ;} catch(problem) { setError(problem instanceof Error? problem.message:"Those images could not be analysed") ;} finally { setAnalysing(false) ;} }
  function removePhoto(id: string) { setPhotos(current => { const next=current.filter(photo => photo.id!==id); const removed=current.find(photo => photo.id===id); if(removed) URL.revokeObjectURL(removed.analysis.preview); return next ;}); setResult(null) ;}
  function generate() { if(!photos.length) { setError("Add at least one clear photo first"); return ;} const frontPhotos=photos.filter(photo => photo.angle==="Front"||photo.angle==="Back"||photo.angle==="Detail"),sidePhotos=photos.filter(photo => photo.angle==="Left"||photo.angle==="Right"),front=mergeProfiles((frontPhotos.length? frontPhotos:photos).map(photo => photo.analysis.profile)),rawSide=mergeProfiles((sidePhotos.length? sidePhotos:photos).map(photo => photo.analysis.profile)),side={ ...rawSide,widths: rawSide.widths.map(value => sidePhotos.length? value:value*.68) },settings=SIZES[size]; const generated=reconstructFromProfiles(front,side,{ name: "Photo reconstruction",heightLayers: settings.layers,maxWidthStuds: settings.width,maxDepthStuds: settings.depth,colour,hollow }); setResult(generated); setStep(0); sessionStorage.setItem("brickforge.generatedAssembly",serializeAssembly(generated.document)) ;}
  function openEditor() { if(!result) return; sessionStorage.setItem("brickforge.generatedAssembly",serializeAssembly(result.document)); window.location.assign("/assembly") ;}
  return <main className="reconstruct-shell">
    <header className="reconstruct-top"><Link className="reconstruct-brand" href="/"><span><Blocks size={20} /></span><strong>BRICKFORGE <i>AI</i></strong></Link><nav><Link className="active" href="/"><ImagePlus size={15} />Photo reconstruction</Link><Link href="/assembly"><Box size={15} />Assembly editor</Link></nav><div className="local-badge"><ShieldCheck size={15} />Photos processed locally</div></header>
    <section className="reconstruct-main">
      <div className="reconstruct-title"><div><p>MULTI-VIEW RECONSTRUCTION · M3.1</p><h1>Turn photographs into a buildable brick study</h1><span>Use several angles for stronger shape estimates. BrickForge converts the shared silhouette into an editable model, parts list, and ordered layers.</span></div><div className="pipeline"><span className="done"><Check />Photos</span><i /><span className={photos.length? "done":""}><Check />Shape</span><i /><span className={result? "done":""}><Check />Build</span></div></div>
      <div className="reconstruct-grid">
        <section className="photo-column">
          <div className="section-label"><span>01</span><div><b>Reference photographs</b><small>Front, rear, and side views work best</small></div><em>{photos.length}/8</em></div>
          <button className={`dropzone ${photos.length? "compact":""}`} onClick={() => input.current?.click()} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); addPhotos(event.dataTransfer.files) ;}}><input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={event => addPhotos(event.target.files)} />{analysing? <LoaderCircle className="spin" size={29} />:<ImagePlus size={29} />}<b>{analysing? "Analysing silhouettes…":photos.length? "Add another angle":"Choose or drop photographs"}</b><span>JPG, PNG, or WebP · up to 8 views</span></button>
          {error&&<div className="reconstruct-error">{error}</div>}
          <div className="photo-list">{photos.map(photo => <article key={photo.id}><Image src={photo.analysis.preview} alt={photo.name} width={58} height={47} unoptimized /><div><b>{photo.name}</b><small>{photo.analysis.width} × {photo.analysis.height} · {Math.round(photo.analysis.profile.confidence*100)}% mask confidence</small><select aria-label={`View angle for ${photo.name}`} value={photo.angle} onChange={event => { const angle=event.target.value as Angle; setPhotos(current => current.map(item => item.id===photo.id? { ...item,angle }:item)); setResult(null) ;}}>{ANGLES.map(angle => <option key={angle}>{angle}</option>)}</select></div><button aria-label={`Remove ${photo.name}`} onClick={() => removePhoto(photo.id)}><Trash2 size={15} /></button></article>)}</div>
          <div className="capture-tips"><Eye size={17} /><div><b>For the cleanest model</b><span>Keep the object centred, use an uncluttered background, and photograph it at roughly the same height from each direction.</span></div></div>
        </section>
        <section className="settings-column">
          <div className="section-label"><span>02</span><div><b>Build target</b><small>Choose fidelity and construction style</small></div></div>
          <label className="setting-title">MODEL SIZE</label><div className="size-options">{Object.entries(SIZES).map(([name,value]) => <button key={name} className={size===name? "selected":""} onClick={() => { setSize(name as keyof typeof SIZES); setResult(null) ;}}><b>{name}</b><span>{value.layers} layers</span><small>up to {value.width} × {value.depth} studs</small></button>)}</div>
          <label className="setting-title">PRIMARY BRICK COLOUR</label><div className="colour-options">{COLOURS.map(value => <button key={value.code} className={colour===value.code? "selected":""} aria-label={value.name} title={value.name} style={{ background: value.hex }} onClick={() => { setColour(value.code); setResult(null) ;}} />)}</div>
          <label className="hollow-toggle"><input type="checkbox" checked={hollow} onChange={event => { setHollow(event.target.checked); setResult(null) ;}} /><span><b>Hollow large sections</b><small>Uses fewer parts while preserving the outer silhouette.</small></span></label>
          <div className="estimate-card"><Sparkles size={18} /><div><b>Silhouette reconstruction</b><span>This milestone estimates shape from image outlines. Fine surface details and hidden cavities will be simplified into a stable brick interpretation.</span></div></div>
          <button className="generate-button" disabled={!photos.length||analysing} onClick={generate}><Sparkles size={17} />{result? "Regenerate model":"Generate brick model"}<ArrowRight size={17} /></button>
        </section>
        <section className={`result-column ${result? "has-result":""}`}>
          <div className="section-label"><span>03</span><div><b>Build package</b><small>Model, inventory, and instructions</small></div></div>
          {!result? <div className="result-empty"><Layers3 size={34} /><b>Your build will appear here</b><span>Add photographs, choose a size, and generate the first automatic brick study.</span></div>:<><div className="result-summary"><div><small>PARTS</small><b>{result.document.parts.length}</b></div><div><small>LAYERS</small><b>{result.instructions.length}</b></div><div><small>SHAPE CONFIDENCE</small><b>{result.confidence}%</b></div></div><div className="result-valid"><ShieldCheck size={18} /><div><b>Editable build generated</b><span>{hollow? "Hollow-shell":"Solid"} construction · {result.occupiedStuds} occupied studs analysed</span></div></div><div className="result-tabs"><button className="selected">Instructions</button><button onClick={openEditor}>Open 3D editor</button></div><div className="instruction-card"><div className="step-heading"><button disabled={step===0} onClick={() => setStep(value => value-1)}>‹</button><span><small>STEP {step+1} OF {result.instructions.length}</small><b>{result.instructions[step].title}</b></span><button disabled={step===result.instructions.length-1} onClick={() => setStep(value => value+1)}>›</button></div><LayerDiagram parts={result.document.parts.filter(part => result.instructions[step].partIds.includes(part.id))} /><ul>{result.instructions[step].summary.map(row => <li key={row.partNumber}><span>Part {row.partNumber}</span><b>× {row.quantity}</b></li>)}</ul></div><div className="mini-bom"><div><b>Complete parts list</b><span>{bom.length} part/colour groups</span></div>{bom.slice(0,5).map(row => <p key={`${row.partNumber}-${row.colour}`}><i style={{ background: COLOURS.find(value => value.code===row.colour)?.hex }} /><span>{row.partNumber} · {row.name}</span><b>×{row.quantity}</b></p>)}</div><div className="result-actions"><button onClick={openEditor}>Edit model <ChevronRight size={15} /></button><button onClick={() => download("brickforge-photo-build.json",JSON.stringify({ assembly: result.document,instructions: result.instructions },null,2),"application/json")}><Download size={15} />Build package</button><button onClick={() => download("brickforge-photo-build.ldr",exportLDraw(result.document),"text/plain")}><Download size={15} />LDraw</button></div></>}
        </section>
      </div>
    </section>
  </main>;
}
